groups:
  - name: workernet_alerts
    rules:
      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"

      # High error rate
      - alert: HighErrorRate
        expr: rate(http_errors_total[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # Database slow queries
      - alert: DatabaseSlowQueries
        expr: histogram_quantile(0.95, rate(db_query_duration_seconds_bucket[5m])) > 5
        for: 3m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Slow database queries detected"
          description: "95th percentile query time is {{ $value }}s"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (memory_usage_bytes / 1024 / 1024 / 1024) > 4
        for: 5m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}GB for {{ $labels.instance }}"

      # High CPU usage
      - alert: HighCPUUsage
        expr: cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          service: backend
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% for {{ $labels.instance }}"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.job }}"
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} service is down on {{ $labels.instance }}"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: db_connection_errors_total > 10
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "Database connection issues"
          description: "{{ $value }} database connection errors detected"

      # Redis connection issues
      - alert: RedisConnectionIssues
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis service is down on {{ $labels.instance }}"

      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Disk space is low"
          description: "Disk space is {{ $value | humanizePercentage }} available on {{ $labels.instance }}"

      # High queue length
      - alert: HighQueueLength
        expr: celery_queue_length > 1000
        for: 5m
        labels:
          severity: warning
          service: celery
        annotations:
          summary: "High queue length detected"
          description: "Queue length is {{ $value }} for {{ $labels.queue }}"

      # Failed tasks
      - alert: HighTaskFailureRate
        expr: rate(celery_tasks_failed_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: celery
        annotations:
          summary: "High task failure rate"
          description: "Task failure rate is {{ $value }} per second"

  - name: workernet_incidents
    rules:
      # Critical system failure
      - alert: CriticalSystemFailure
        expr: up == 0 and on(instance) group_left() (up{job="workernet-backend"} == 0)
        for: 30s
        labels:
          severity: critical
          incident_type: system_failure
        annotations:
          summary: "Critical system failure"
          description: "Multiple services are down, potential system-wide failure"

      # Data corruption
      - alert: DataCorruption
        expr: increase(db_errors_total[5m]) > 50
        for: 1m
        labels:
          severity: critical
          incident_type: data_corruption
        annotations:
          summary: "Potential data corruption"
          description: "High number of database errors detected: {{ $value }}"

      # Security breach
      - alert: SecurityBreach
        expr: rate(http_requests_total{status_code=~"4.."}[5m]) > 100
        for: 2m
        labels:
          severity: critical
          incident_type: security_breach
        annotations:
          summary: "Potential security breach"
          description: "High rate of 4xx errors: {{ $value }} per second"

  - name: workernet_sla
    rules:
      # SLA violation - response time
      - alert: SLAViolationResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[1h])) > 1
        for: 0m
        labels:
          severity: warning
          sla_metric: response_time
        annotations:
          summary: "SLA violation: Response time"
          description: "95th percentile response time exceeded 1s over the last hour"

      # SLA violation - availability
      - alert: SLAViolationAvailability
        expr: (up == 0) and (time() - up == 0) > 300
        for: 0m
        labels:
          severity: critical
          sla_metric: availability
        annotations:
          summary: "SLA violation: Availability"
          description: "Service has been down for more than 5 minutes"
